### ISSUE TITLE
Animation mode won't allow moving verticies on Linux

### ISSUE THREAD

**Issue by NeonSRB2** [zturtleman/mm3d#192] opened 2023-12-18 17:18 UTC
This is happening on whatever is being put on Zorin OS' "software"

![image](https://github.com/zturtleman/mm3d/assets/118679101/7939202b-e3fb-4d51-a567-db1000b8c278)

**Comment by zturtleman** [comment] 2023-12-19 02:27
Is it a frame animation? In skeletal animations you can only move bones.

**Comment by NeonSRB2** [comment] 2023-12-30 03:24
frame animation, sorry I hadn't mentioned that...

**Comment by zturtleman** [comment] 2024-01-04 09:22
Maybe there is a misunderstanding how it works. It worked for me in ZorinOS 16.3 in a virtual machine. Video demo:

https://github.com/zturtleman/mm3d/assets/405505/af83f6e8-f552-4717-92e6-6d4b05fc3cb1

I had some issues using the mouse to move the slider for selecting the animation frame and used the arrow keys. I think this improved some in later versions.

**Comment by zturtleman** [comment] 2024-07-20 09:09
Closing issue as I'm unable to reproduce the issue. If this is still a problem, you can comment.

**Closed by zturtleman** 2024-07-20 09:09 UTC
