### ISSUE TITLE
I want to report one issue and one question

### ISSUE THREAD

**Issue by gnubsdguy** [zturtleman/mm3d#190] opened 2023-07-10 11:15 UTC
Hi There

I have one issue and I have one question.

The issue is the following:

When I open two instances of the program (I open the program twice because i want to do different things) if i want to just one from the file menu when I press close then it will close the program completely (The close option will close all the program completely and not just one of them).

My question is : I want to make some Quake MD2 models with very simple textures of faces, so for example if I want to make a ball with one face then if I add one texture with one face then the ball will appear to have two faces (one face in the front and one face in the back). Do you have in the mm3d a manual how to add a texture to a Quake MD2 model ?

**Comment by zturtleman** [comment] 2023-07-10 15:17
Hmm, I can't reproduce Close in File menu closing all windows on Debian 11. (Quit is suppose to but Close should not.) What Maverick version and operating system are you using?

----

Quake 2 MD2 only supports one texture/material for the model so all faces would need to be in one image. (Quake 3 MD3 supports multiple.) Additional materials are exported as MD2 skins that the game could switch to.

### Materials
You can create a material in menu -> Materials -> Edit Materials... -> New Material -> (material name isn't exported to MD2) and then click Set Texture... to assign the texture.

### Groups
Select all geometry and create a group (mesh) in menu -> Materials -> Edit Groups... -> New -> (group name isn't exported to MD2) and then click Faces: Add To Group and set "Texture" to the material you created. ("Texture" here should really be Material.)

For two textures—which can't be used with MD2—you would create two groups and materials, assign half of the sphere to each group, and set different materials.

### Texture Coordinates
For both sides to display the exact same texture or if two textures are used; There is menu -> Materials -> Edit Texture Coordinates... and with Map Scheme: Group, click Reset Coordinates. This will make two sides display the same image. This doesn't allow two unique face images with one texture but it would if using multiple textures.

The whole sphere can have a unique texture; Select Create Texture Projector at the far right side of the toolbar and then click in the middle of the sphere and drag to the edge of sphere. Select all geometry and then go to menu -> Materials -> Edit Projection... and click Add Faces to Projection and Apply Projection. (I don't really know how best to set the projector up well for good texture coordinates; the dark green line is the texture seam I think.)

Use menu -> Materials -> Paint Texture... to export the UV map for reference to apply faces to both sides of the sphere texture.

### Export
The texture filename written to the MD2 model is MD2_PATH metadata followed by the texture filename (MD2_PATH + / + texture_basename.pcx). You can set MD2_PATH in menu -> Model -> Edit Metadata... -> New and then set key to MD2_PATH and set value to the directory in the Quake filesystem (for example, models/players/sarge).

This is kind of bizarre. I hope to change it to use the material name eventually.

(MD3 export uses MD3_PATH instead.)

**Comment by gnubsdguy** [comment] 2023-07-10 15:37
I am using Debian Buster 11 x64 and the version of the MM3D (I didn't download the binary i just compiled the program myself) is this one : 1.3.12. Thanks again for help!

**Comment by zturtleman** [comment] 2023-07-14 13:30
> I am using Debian Buster 11 x64

Those Debian codename and version do not match. For clarification, are you using Debian 10 (Buster) or Debian 11 (Bullseye)?

**Comment by gnubsdguy** [comment] 2023-07-15 21:15
Debian 11 Bullseye but it seems that the issue has been resolved and thanks for help !

**Comment by zturtleman** [comment] 2023-07-16 13:19
Okay. I'm glad it worked out.

**Closed by zturtleman** 2023-07-16 13:19 UTC
Labels: discussion
